// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/ps_monitor.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time  int64  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Text  string `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Match bool   `protobuf:"varint,3,opt,name=match,proto3" json:"match,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ps_monitor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ps_monitor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_ps_monitor_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Event) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Event) GetMatch() bool {
	if x != nil {
		return x.Match
	}
	return false
}

type ConfigChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pattern       string `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	ReceiveOutput bool   `protobuf:"varint,2,opt,name=receiveOutput,proto3" json:"receiveOutput,omitempty"`
}

func (x *ConfigChange) Reset() {
	*x = ConfigChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ps_monitor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigChange) ProtoMessage() {}

func (x *ConfigChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ps_monitor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigChange.ProtoReflect.Descriptor instead.
func (*ConfigChange) Descriptor() ([]byte, []int) {
	return file_proto_ps_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigChange) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *ConfigChange) GetReceiveOutput() bool {
	if x != nil {
		return x.ReceiveOutput
	}
	return false
}

type ConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Payload:
	//	*ConfigRequest_PipeName
	//	*ConfigRequest_Config
	Payload isConfigRequest_Payload `protobuf_oneof:"payload"`
}

func (x *ConfigRequest) Reset() {
	*x = ConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ps_monitor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRequest) ProtoMessage() {}

func (x *ConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ps_monitor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigRequest.ProtoReflect.Descriptor instead.
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_ps_monitor_proto_rawDescGZIP(), []int{2}
}

func (m *ConfigRequest) GetPayload() isConfigRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *ConfigRequest) GetPipeName() string {
	if x, ok := x.GetPayload().(*ConfigRequest_PipeName); ok {
		return x.PipeName
	}
	return ""
}

func (x *ConfigRequest) GetConfig() *ConfigChange {
	if x, ok := x.GetPayload().(*ConfigRequest_Config); ok {
		return x.Config
	}
	return nil
}

type isConfigRequest_Payload interface {
	isConfigRequest_Payload()
}

type ConfigRequest_PipeName struct {
	PipeName string `protobuf:"bytes,1,opt,name=pipeName,proto3,oneof"`
}

type ConfigRequest_Config struct {
	Config *ConfigChange `protobuf:"bytes,2,opt,name=config,proto3,oneof"`
}

func (*ConfigRequest_PipeName) isConfigRequest_Payload() {}

func (*ConfigRequest_Config) isConfigRequest_Payload() {}

type ConfigOnceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PipeName string        `protobuf:"bytes,1,opt,name=pipeName,proto3" json:"pipeName,omitempty"`
	Config   *ConfigChange `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ConfigOnceRequest) Reset() {
	*x = ConfigOnceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ps_monitor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigOnceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigOnceRequest) ProtoMessage() {}

func (x *ConfigOnceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ps_monitor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigOnceRequest.ProtoReflect.Descriptor instead.
func (*ConfigOnceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ps_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigOnceRequest) GetPipeName() string {
	if x != nil {
		return x.PipeName
	}
	return ""
}

func (x *ConfigOnceRequest) GetConfig() *ConfigChange {
	if x != nil {
		return x.Config
	}
	return nil
}

var File_proto_ps_monitor_proto protoreflect.FileDescriptor

var file_proto_ps_monitor_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x73, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x73, 0x5f, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x22, 0x45, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x22, 0x4e, 0x0a, 0x0c, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x61, 0x74, 0x74, 0x65, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61,
	0x74, 0x74, 0x65, 0x72, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65,
	0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x72, 0x65,
	0x63, 0x65, 0x69, 0x76, 0x65, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x6c, 0x0a, 0x0d, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x08,
	0x70, 0x69, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x32, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x73, 0x5f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x61, 0x0a, 0x11, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x69, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x69, 0x70, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x73, 0x5f,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x32, 0x88, 0x01, 0x0a,
	0x0e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12,
	0x37, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x19, 0x2e, 0x70, 0x73, 0x5f, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x11, 0x2e, 0x70, 0x73, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3d, 0x0a, 0x07, 0x52, 0x75, 0x6e, 0x4f,
	0x6e, 0x63, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x73, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4f, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x70, 0x73, 0x5f, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ps_monitor_proto_rawDescOnce sync.Once
	file_proto_ps_monitor_proto_rawDescData = file_proto_ps_monitor_proto_rawDesc
)

func file_proto_ps_monitor_proto_rawDescGZIP() []byte {
	file_proto_ps_monitor_proto_rawDescOnce.Do(func() {
		file_proto_ps_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ps_monitor_proto_rawDescData)
	})
	return file_proto_ps_monitor_proto_rawDescData
}

var file_proto_ps_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ps_monitor_proto_goTypes = []interface{}{
	(*Event)(nil),             // 0: ps_monitor.Event
	(*ConfigChange)(nil),      // 1: ps_monitor.ConfigChange
	(*ConfigRequest)(nil),     // 2: ps_monitor.ConfigRequest
	(*ConfigOnceRequest)(nil), // 3: ps_monitor.ConfigOnceRequest
}
var file_proto_ps_monitor_proto_depIdxs = []int32{
	1, // 0: ps_monitor.ConfigRequest.config:type_name -> ps_monitor.ConfigChange
	1, // 1: ps_monitor.ConfigOnceRequest.config:type_name -> ps_monitor.ConfigChange
	2, // 2: ps_monitor.ProcessMonitor.Run:input_type -> ps_monitor.ConfigRequest
	3, // 3: ps_monitor.ProcessMonitor.RunOnce:input_type -> ps_monitor.ConfigOnceRequest
	0, // 4: ps_monitor.ProcessMonitor.Run:output_type -> ps_monitor.Event
	0, // 5: ps_monitor.ProcessMonitor.RunOnce:output_type -> ps_monitor.Event
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ps_monitor_proto_init() }
func file_proto_ps_monitor_proto_init() {
	if File_proto_ps_monitor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ps_monitor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ps_monitor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ps_monitor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ps_monitor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigOnceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_ps_monitor_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ConfigRequest_PipeName)(nil),
		(*ConfigRequest_Config)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ps_monitor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ps_monitor_proto_goTypes,
		DependencyIndexes: file_proto_ps_monitor_proto_depIdxs,
		MessageInfos:      file_proto_ps_monitor_proto_msgTypes,
	}.Build()
	File_proto_ps_monitor_proto = out.File
	file_proto_ps_monitor_proto_rawDesc = nil
	file_proto_ps_monitor_proto_goTypes = nil
	file_proto_ps_monitor_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProcessMonitorClient is the client API for ProcessMonitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessMonitorClient interface {
	Run(ctx context.Context, opts ...grpc.CallOption) (ProcessMonitor_RunClient, error)
	RunOnce(ctx context.Context, in *ConfigOnceRequest, opts ...grpc.CallOption) (ProcessMonitor_RunOnceClient, error)
}

type processMonitorClient struct {
	cc grpc.ClientConnInterface
}

func NewProcessMonitorClient(cc grpc.ClientConnInterface) ProcessMonitorClient {
	return &processMonitorClient{cc}
}

func (c *processMonitorClient) Run(ctx context.Context, opts ...grpc.CallOption) (ProcessMonitor_RunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProcessMonitor_serviceDesc.Streams[0], "/ps_monitor.ProcessMonitor/Run", opts...)
	if err != nil {
		return nil, err
	}
	x := &processMonitorRunClient{stream}
	return x, nil
}

type ProcessMonitor_RunClient interface {
	Send(*ConfigRequest) error
	Recv() (*Event, error)
	grpc.ClientStream
}

type processMonitorRunClient struct {
	grpc.ClientStream
}

func (x *processMonitorRunClient) Send(m *ConfigRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *processMonitorRunClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *processMonitorClient) RunOnce(ctx context.Context, in *ConfigOnceRequest, opts ...grpc.CallOption) (ProcessMonitor_RunOnceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProcessMonitor_serviceDesc.Streams[1], "/ps_monitor.ProcessMonitor/RunOnce", opts...)
	if err != nil {
		return nil, err
	}
	x := &processMonitorRunOnceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProcessMonitor_RunOnceClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type processMonitorRunOnceClient struct {
	grpc.ClientStream
}

func (x *processMonitorRunOnceClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProcessMonitorServer is the server API for ProcessMonitor service.
type ProcessMonitorServer interface {
	Run(ProcessMonitor_RunServer) error
	RunOnce(*ConfigOnceRequest, ProcessMonitor_RunOnceServer) error
}

// UnimplementedProcessMonitorServer can be embedded to have forward compatible implementations.
type UnimplementedProcessMonitorServer struct {
}

func (*UnimplementedProcessMonitorServer) Run(ProcessMonitor_RunServer) error {
	return status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (*UnimplementedProcessMonitorServer) RunOnce(*ConfigOnceRequest, ProcessMonitor_RunOnceServer) error {
	return status.Errorf(codes.Unimplemented, "method RunOnce not implemented")
}

func RegisterProcessMonitorServer(s *grpc.Server, srv ProcessMonitorServer) {
	s.RegisterService(&_ProcessMonitor_serviceDesc, srv)
}

func _ProcessMonitor_Run_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessMonitorServer).Run(&processMonitorRunServer{stream})
}

type ProcessMonitor_RunServer interface {
	Send(*Event) error
	Recv() (*ConfigRequest, error)
	grpc.ServerStream
}

type processMonitorRunServer struct {
	grpc.ServerStream
}

func (x *processMonitorRunServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func (x *processMonitorRunServer) Recv() (*ConfigRequest, error) {
	m := new(ConfigRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProcessMonitor_RunOnce_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConfigOnceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProcessMonitorServer).RunOnce(m, &processMonitorRunOnceServer{stream})
}

type ProcessMonitor_RunOnceServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type processMonitorRunOnceServer struct {
	grpc.ServerStream
}

func (x *processMonitorRunOnceServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _ProcessMonitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ps_monitor.ProcessMonitor",
	HandlerType: (*ProcessMonitorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Run",
			Handler:       _ProcessMonitor_Run_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RunOnce",
			Handler:       _ProcessMonitor_RunOnce_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/ps_monitor.proto",
}
